namespace P5CCS.Editor.Completion;

public static class P5ApiCatalog
{
    public static readonly IReadOnlyList<P5ApiEntry> Entries = new List<P5ApiEntry>
    {
        new("setup", "setup()", "Called once when the program starts. Used to define initial environment properties such as screen size."),
        new("draw", "draw()", "Called directly after setup(), then continuously executes the code within its block until the program is stopped or noLoop() is called."),
        new("preload", "preload()", "Called before setup(). Used to load external assets (images, fonts, sounds) before the sketch starts."),
        new("createCanvas", "createCanvas(width, height, [renderer])", "Creates a canvas element in the document, sized width x height pixels."),
        new("resizeCanvas", "resizeCanvas(width, height)", "Resizes the canvas to the given width and height."),
        new("background", "background(color)", "Sets the color used for the background of the canvas."),
        new("clear", "clear()", "Clears the pixels on the canvas, making every pixel 100% transparent."),
        new("colorMode", "colorMode(mode, [max1], [max2], [max3], [maxA])", "Changes the way p5.js interprets color data (RGB, HSB, or HSL)."),
        new("fill", "fill(color)", "Sets the color used to fill shapes."),
        new("noFill", "noFill()", "Disables filling geometry."),
        new("stroke", "stroke(color)", "Sets the color used to draw lines and borders around shapes."),
        new("noStroke", "noStroke()", "Disables drawing the stroke (outline)."),
        new("strokeWeight", "strokeWeight(weight)", "Sets the width of the stroke used for lines, points, and the border around shapes, in pixels."),
        new("rect", "rect(x, y, w, [h])", "Draws a rectangle on the canvas."),
        new("ellipse", "ellipse(x, y, w, [h])", "Draws an ellipse (oval) to the canvas."),
        new("circle", "circle(x, y, d)", "Draws a circle to the canvas, given a center point and diameter."),
        new("square", "square(x, y, s)", "Draws a square to the canvas, given the top-left corner and side length."),
        new("line", "line(x1, y1, x2, y2)", "Draws a line (a direct path between two points) on the canvas."),
        new("point", "point(x, y)", "Draws a point, a coordinate in space at the dimension of one pixel."),
        new("triangle", "triangle(x1, y1, x2, y2, x3, y3)", "Draws a triangle to the canvas."),
        new("arc", "arc(x, y, w, h, start, stop, [mode])", "Draws an arc to the canvas."),
        new("beginShape", "beginShape([kind])", "Begins recording vertices for a custom shape."),
        new("endShape", "endShape([mode])", "Stops recording vertices for a custom shape."),
        new("vertex", "vertex(x, y)", "Adds a vertex to a custom shape between beginShape() and endShape()."),
        new("translate", "translate(x, y, [z])", "Moves the origin point of the coordinate system."),
        new("rotate", "rotate(angle)", "Rotates the coordinate system."),
        new("scale", "scale(s)", "Scales the coordinate system."),
        new("push", "push()", "Saves the current drawing style settings and transformations."),
        new("pop", "pop()", "Restores the drawing style settings and transformations previously saved by push()."),
        new("text", "text(str, x, y)", "Draws text to the canvas."),
        new("textFont", "textFont(font)", "Sets the current font for text rendering."),
        new("textSize", "textSize(size)", "Sets the current font size."),
        new("textAlign", "textAlign(horizAlign, [vertAlign])", "Sets the alignment of text."),
        new("random", "random([min], [max])", "Returns a random floating point number."),
        new("randomSeed", "randomSeed(seed)", "Sets the seed value for random()."),
        new("noise", "noise(x, [y], [z])", "Returns a Perlin noise value."),
        new("map", "map(value, start1, stop1, start2, stop2)", "Re-maps a number from one range to another."),
        new("constrain", "constrain(n, low, high)", "Constrains a value between a minimum and maximum value."),
        new("dist", "dist(x1, y1, x2, y2)", "Calculates the distance between two points."),
        new("lerp", "lerp(start, stop, amt)", "Calculates a number between two numbers at a specific increment."),
        new("radians", "radians(degrees)", "Converts a degree measurement to its corresponding value in radians."),
        new("degrees", "degrees(radians)", "Converts a radian measurement to its corresponding value in degrees."),
        new("min", "min(value1, value2)", "Returns the smallest value in a sequence of numbers."),
        new("max", "max(value1, value2)", "Returns the largest value in a sequence of numbers."),
        new("floor", "floor(n)", "Rounds a number down to the nearest integer value."),
        new("ceil", "ceil(n)", "Rounds a number up to the nearest integer value."),
        new("round", "round(n)", "Rounds a number to the nearest integer."),
        new("sqrt", "sqrt(n)", "Calculates the square root of a number."),
        new("sin", "sin(angle)", "Calculates the sine of an angle."),
        new("cos", "cos(angle)", "Calculates the cosine of an angle."),
        new("createVector", "createVector([x], [y], [z])", "Creates a new p5.Vector."),
        new("color", "color(gray|r, [g], [b], [a])", "Creates a color from RGB, HSB, or HSL values."),
        new("frameRate", "frameRate([fps])", "Sets or returns the target frame rate of the sketch."),
        new("loadImage", "loadImage(path)", "Loads an image from a path and returns a p5.Image."),
        new("image", "image(img, x, y, [w], [h])", "Draws an image to the canvas."),
        new("imageMode", "imageMode(mode)", "Sets how images are drawn relative to their position: CORNER, CORNERS, or CENTER."),
        new("mousePressed", "mousePressed()", "Called once after a mouse button is pressed."),
        new("mouseReleased", "mouseReleased()", "Called once after a mouse button is released."),
        new("mouseDragged", "mouseDragged()", "Called when the mouse moves while a button is pressed."),
        new("mouseMoved", "mouseMoved()", "Called every time the mouse moves and a mouse button is not pressed."),
        new("keyPressed", "keyPressed()", "Called once every time a key is pressed."),
        new("keyReleased", "keyReleased()", "Called once every time a key is released."),
        new("noLoop", "noLoop()", "Stops p5.js from continuously executing draw()."),
        new("loop", "loop()", "Resumes continuous execution of draw() after noLoop() was called."),
        new("redraw", "redraw([n])", "Executes draw() one or more times, useful with noLoop()."),
        new("width", "width", "System variable containing the width of the canvas in pixels."),
        new("height", "height", "System variable containing the height of the canvas in pixels."),
        new("mouseX", "mouseX", "System variable containing the current horizontal position of the mouse relative to the canvas."),
        new("mouseY", "mouseY", "System variable containing the current vertical position of the mouse relative to the canvas."),
        new("frameCount", "frameCount", "System variable containing the number of frames displayed since the program started."),
        new("PI", "PI", "Mathematical constant PI (approximately 3.14159)."),
        new("TWO_PI", "TWO_PI", "Mathematical constant equal to 2 * PI."),
        new("CENTER", "CENTER", "Constant used for alignment and shape/image drawing modes."),
        new("WEBGL", "WEBGL", "Constant used with createCanvas() to enable 3D WebGL rendering."),
    };
}
