<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FFMpegCore" Version="5.1.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\P5CCS.Core\P5CCS.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\resources\ffmpeg\ffmpeg.exe"
          Link="tools\ffmpeg\ffmpeg.exe"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\resources\ffmpeg\LICENSE.txt"
          Link="tools\ffmpeg\LICENSE.txt"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
