<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.0.90" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\P5CCS.Core\P5CCS.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Highlighting\P5JavaScriptDark.xshd" LogicalName="P5CCS.Editor.Highlighting.P5JavaScriptDark.xshd" />
    <EmbeddedResource Include="Highlighting\P5JavaScriptLight.xshd" LogicalName="P5CCS.Editor.Highlighting.P5JavaScriptLight.xshd" />
  </ItemGroup>

</Project>
